drop table if exists users cascade;

create table if not exists users (
    id integer generated by default as identity(start with 1, increment by 1) primary key,
    email varchar(50) not null,
	password varchar(50) not null
);